theme: jekyll-theme-minimal

title: tethered.network
description: 
author: Sarah Ciston


# logo: 
# show_downloads: 
# google_analytics: 

links: 
  "Intersectional AI Toolkit": 
      - "https://sarahciston.github.io/intersectionalai"
  "Coding.Care": 
    - "https://sarahciston.github.io/codingcare"
  "More projects": 
    - "https://sarahciston.github.io"
links_new_tab: true

## prose.io config
prose:
  rooturl: '_posts'
  siteurl: 'https://sarahciston.github.io/sarahciston/tethered'
  # relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: 'assets/img'
  metadata:
    _posts:
    	- name: "date"
            field:
              element: "number"
              label: "date"
              type: "number"
        - name: "nav_order"
        	field:
            	element: "number"
                label: "nav_order"
                type: "number"
        - name: "title"
            field:
              element: "text"
              label: "title"
              type: "text"

