theme: jekyll-theme-minimal

title: tethered.network
description: a platform experiment
author: Sarah Ciston


# logo: 
# show_downloads: 
# google_analytics: 

links: 
  "Intersectional AI Toolkit": 
    - "https://sarahciston.github.io/intersectionalai"
  "Coding.Care": 
    - "https://sarahciston.github.io/codingcare"
  "More projects": 
    - "https://sarahciston.github.io"
links_new_tab: true

## prose.io config
prose:
  rooturl: 'posts'
  siteurl: 'https://sarahciston.github.io/sarahciston/tethered'
  media: 'assets/img'
  metadata:
    posts:
      - name: "layout"
        field: 
          element: "hidden"
          value: "default"
      - name: "date"
        field:
          element: "number"
          label: "date"
          value: CURRENT_DATETIME
          type: "number"
      - name: "nav_order"
        field:
          element: "number"
          label: "nav_order"
          type: "number"
      - name: "title"
        field:
          element: "text"
          label: "title"
          type: "text"
    #users:
      #- login: "sarahciston"
      #  user: "Sarah Ciston"
