theme: jekyll-theme-minimal

title: tethered.network
description: every dissertation starts somewhere | bless this mess 


# logo: 
# show_downloads: 
# google_analytics: 

links: 
  "Intersectional AI Toolkit": 
      - "https://sarahciston.github.io/intersectionalai"
  "Coding.Care": 
    - "https://sarahciston.github.io/codingcare"
  "More projects": 
    - "https://sarahciston.github.io"
links_new_tab: true


